"""empty message

Revision ID: dd1c69b478e3
Revises: 78ba302e3a5c
Create Date: 2018-12-14 15:52:29.638023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd1c69b478e3'
down_revision = '78ba302e3a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hive_tbl_statistic_history_ext',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('metric_key', sa.String(length=80), nullable=False),
    sa.Column('metric_value', sa.String(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'metric_key', 'date', name='unique_id_key_date')
    )
    op.create_index('index_id_date', 'hive_tbl_statistic_history_ext', ['id', 'date'], unique=False)
    op.alter_column('score', 'score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'score', 'cource', ['cource_id'], ['id'])
    op.create_foreign_key(None, 'score', 'student', ['student_id'], ['id'])
    op.drop_column('score', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'score', type_='foreignkey')
    op.drop_constraint(None, 'score', type_='foreignkey')
    op.alter_column('score', 'score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_index('index_id_date', table_name='hive_tbl_statistic_history_ext')
    op.drop_table('hive_tbl_statistic_history_ext')
    # ### end Alembic commands ###
