"""empty message

Revision ID: ea70c2ce6a17
Revises: b6e03b193fb7
Create Date: 2018-12-02 22:15:13.583495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea70c2ce6a17'
down_revision = 'b6e03b193fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('cource_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cource_id'], ['cource.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['student.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    # ### end Alembic commands ###
