"""empty message

Revision ID: fef5e857b973
Revises: 8542437a8f35
Create Date: 2018-12-02 19:31:19.159837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef5e857b973'
down_revision = '8542437a8f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cource', 'teacher', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cource', type_='foreignkey')
    # ### end Alembic commands ###
